title : Leorez Blog
description: 'Full stack programmer Leorez Blog'

markdown: kramdown
highlighter: rouge
logo: true
paginate: 15
baseurl: /
plugins: [jekyll-gist,jekyll-feed]
permalink: /:year/:month/:title.html
